# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 16) do

  create_table "people", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "email",      :string
    t.column "username",   :string
  end

  create_table "project_statuses", :force => true do |t|
    t.column "status", :string
  end

  create_table "projects", :force => true do |t|
    t.column "name",              :string
    t.column "description",       :text
    t.column "date_founded",      :date
    t.column "project_status_id", :integer
    t.column "status_date",       :date
  end

  create_table "team_members", :force => true do |t|
    t.column "person_id",  :integer
    t.column "role",       :string
    t.column "date_on",    :date
    t.column "date_off",   :date
    t.column "project_id", :integer
  end

  create_table "ticket_categories", :force => true do |t|
    t.column "category", :string
  end

  create_table "ticket_comments", :force => true do |t|
    t.column "comment",     :text
    t.column "date_posted", :datetime
    t.column "ticket_id",   :integer
    t.column "person_id",   :integer
  end

  create_table "ticket_resolutions", :force => true do |t|
    t.column "resolution", :string
  end

  create_table "ticket_tags", :force => true do |t|
    t.column "tag",       :string
    t.column "ticket_id", :integer
  end

  create_table "tickets", :force => true do |t|
    t.column "ticket_category_id",   :integer
    t.column "description",          :text
    t.column "project_id",           :integer
    t.column "priority",             :integer
    t.column "date_assigned",        :datetime
    t.column "submitted_by",         :string
    t.column "date_submitted",       :datetime
    t.column "date_resolved",        :datetime
    t.column "ticket_resolution_id", :string
    t.column "parent_bug_id",        :integer
    t.column "assigned_person_id",   :integer
  end

  create_table "users", :force => true do |t|
    t.column "username",        :string, :null => false
    t.column "hashed_password", :string
  end

end
